### ISSUE TITLE
embed doesn't work with IIIF image url (info.json)

### ISSUE THREAD

**Issue by jeau** [adnodev/adno#28]
The embed code (iframe) works fine with adno project or static image URL but not with IIIF image URL (info.json file) 

cf https://static.emf.fr/adno/embed/exemple.html

```
<iframe src="https://w.adno.app/#/embed?url=https://iiif.mexina.fr/iiif/3/KISE0%2FcalAo.json" height="400px" width="100%" ></iframe>
```

**Comment by sebprunierserli** [comment]
It's probably because le URL `https://iiif.mexina.fr/iiif/3/KISE0/calAo.json/info.json` returns a 404 error.

**Comment by jeau** [comment]
yes, you're right about this URL, there is a server problem 

however it still doesn't work with this url which is valid
https://horae-pictavenses.fr/iiif-img/9838/info.json

I've updated the example page https://static.emf.fr/adno/embed/exemple.html

**Comment by Zwiterrion** [comment]
https://static.emf.fr/adno/embed/exemple.html give me an `File or directory not found`

**Comment by jeau** [comment]
here's a new page showing the issue

https://tools.mexina.fr/adno/embed/

The embed work's fine with https://horae-pictavenses.fr/iiif-img/9838/info.json

but not with https://iiif.mexina.fr/iiif/3/KISE0%2FcalAqiWA38.jpg/info.json 

however, this url works directly in Adno

The purpose of this trick is to be able to use the embed as a simple viewer of an IIIF image without annotations.
