### ISSUE TITLE
Embed viewer: full screen and toolbar parameter not working 

### ISSUE THREAD

**Issue by jeau** [adnodev/adno#31]
Fullscreen no longer works in the iframe, either with the `allow="fullscreen"` attribute or `allowfullscreen="true"` attribute (obsolete). Is there a possible fullscreen parameter in the URL? In any case, it's not documented with the others.

The toolbar setting does not seem to work

**Comment by sebprunierserli** [comment]
The error is : 

![image](https://github.com/adnodev/adno/assets/17246464/f37ff738-374d-46c8-9e1d-d77bc4220440)
