### ISSUE TITLE
Importation de certains manifestes IIIF depuis gallica impossible

### ISSUE THREAD

**Issue by pprw** [adnodev/adno#43]
Bonjour,

Certains manifestes IIIF de gallica ne s'importent pas dans adno.

Exemple : https://gallica.bnf.fr/iiif/ark:/12148/btv1b77421709/manifest.json

![bug_adno](https://github.com/adnodev/adno/assets/5262986/81091548-486e-4e5d-a5d9-8940237cffd9)

La page reste indéfiniment sur le bouton "Annuler et revenir à l'accueil".

Constaté avec une classe d'étudiant (donc sur plusieurs ordinateurs, navigateurs et avec des manifestes différents).

**Comment by pprw** [comment]
Constaté également aujourd'hui dans un autre cadre

**Comment by jeau** [comment]
Même problème avec des documents de la Library Of Congress

celui-ci fonctionne : https://www.loc.gov/item/2021666122/manifest.json 

celui-ci aussi : https://www.loc.gov/item/2021667602/manifest.json 

mais pas celui-là : https://www.loc.gov/item/2021668945/manifest.json
